### ISSUE TITLE
Fix feedback section

### ISSUE THREAD

**Issue by sayanee** [sauvc/sauvc.github.io#1]
- remove bullets - change into 1 sentence / paragraph `<p>`
- remove over-complicated 2 sentences into 1 sentence - slash all redundancy!

![image](https://user-images.githubusercontent.com/413879/41091608-8748bb6a-6a79-11e8-8b62-724fd959006d.png)

**Comment by sayanee** [comment]
Sorry this is for https://github.com/sauvc/rulebook repository 😭

**Comment by notthetup** [comment]
Fixed in https://github.com/sauvc/rulebook/commit/0caf3588c1e43754f175eeaf89346112185cdbc5
