### ISSUE TITLE
Update Saturday schedule to include Introduction to U/W robotics talk, Guided tour and ROS meetup,

### ISSUE THREAD

**Issue by harivnkochi** [sauvc/sauvc.github.io#13]
- Saturday schedule to include Introduction to U/W robotics talk, Guided tour and ROS meetup,

**Comment by notthetup** [comment]
What is the time and venue for Guided Tour and ROS Meetup? @harivnkochi @rajmis

**Comment by harivnkochi** [comment]
Will forward an email to you with detailed schedule

**Comment by harivnkochi** [comment]
detailed schedule (pulled from the eventbrite link: https://www.eventbrite.sg/e/singapore-auv-challenge-tickets-57583246039?aff=ebdssbdestsearch&fbclid=IwAR3WALzUq2KXCqTHhqGkTplnne7qqaRtBJzo7zfWXHdSWX9LcZYpTGB3TcQ )

Introductory Workshop on Underwater Robotics - March 9, 2019 @ 13:00
Guided Tours - March 9, 2019 @ 14:00
ROS Meetup - March 9, 2019 @15:00
