### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by senceryazici** [sauvc/sauvc.github.io#28]
Hello, 
The İTÜ auv Team website is not provided as I see,  

For English: http://auv.itu.edu.tr/index-eng.html

Original(Turkish): auv.itu.edu.tr

 In line: 
https://github.com/sauvc/sauvc.github.io/blob/0ed8f31e7851dad9c9e8fb837ed2dfacff851e79/_data/registered.yml#L837

**Comment by notthetup** [comment]
Thanks, @senceryazici. Adding it now.
