### ISSUE TITLE
Labels and Typos

### ISSUE THREAD

**Issue by notthetup** [sauvc/sauvc.github.io#5]
- Qualified Teams -> Selected Teams
- > Just noticed a typo on the page now. "Detailed explaination... "

**Comment by harivnkochi** [comment]
- Remove 'Registration closed' Tab at the top?

**Comment by harivnkochi** [comment]
> * Qualified Teams -> Selected Teams

As per discussion in whatsapp, 
* Qualified Teams -> Short-listed Teams

**Comment by notthetup** [comment]
Fixed.
