### ISSUE TITLE
ONR logo appears again apart from ONRG logo in sponsors list

### ISSUE THREAD

**Issue by harivnkochi** [sauvc/sauvc.github.io#6]
I believe we got sponsorship from ONRG (ONR Global), not ONR (these 2 are different entities). But I see ONR logo re-appears down the list

**Comment by notthetup** [comment]
So we only got sponsored by ONRG? Not ONR? I think there was some miscomms.

**Comment by harivnkochi** [comment]
im so sorry, just checked with venu to confirm. apparently its more complicated than i thought. both onr and onrg contributed, but the money is coming in the name of onrg. 
so lets leave both the logos on the website
sorry about the confusion, it was misunderstanding on my part.
