### ISSUE TITLE
Expired pages and domains

### ISSUE THREAD

**Issue by ahmd-mahm** [sauvc/sauvc.github.io#7]
URLs (and the associated descriptions) linked via the text "Nets Flash Pay card" and "Boxyroom" need to be removed as the page and domain have expired, respectively. Also, since "Uber" is no longer used in Singapore, any mentioning of it can be removed from the website.

![image](https://user-images.githubusercontent.com/19687045/52851546-5fbf5f00-3151-11e9-96f2-bcd1eac78372.png)

**Comment by notthetup** [comment]
Thanks. 

Ideally, it would be awesome to add something like this to check for dead links. Will try to integrate it over the weekend.

https://github.com/notthetup/awesome-webaudio/blob/master/.travis.yml

**Comment by notthetup** [comment]
Added in 3019b10
